const button1 = document.getElementById('button1')
const button2 = document.getElementById('button2')
const button3 = document.getElementById('button3')
const button4 = document.getElementById('button4')
const button5 = document.getElementById('button5')

let photoDivOne = document.getElementById('firstBox')
let photoDivTwo = document.getElementById('secondBox')
let photoDivThree = document.getElementById('thirdBox')
let photoDivFour = document.getElementById('fourthBox')

button1.addEventListener('click',()=>{
    photoDivOne.style.width=("400px")
    document.getElementById('photo1').style.width=('400px')
    photoDivTwo.style.width=("50px")
    document.getElementById('photo2').style.width=('50px')
    photoDivThree.style.width=("50px")
    document.getElementById('photo3').style.width=('50px')
    photoDivFour.style.width=("50px")
    document.getElementById('photo4').style.width=('50px')
})